# Comparisons {#comparisons}

## Need for a unit of child development

Many disciplines study child development in order to answer clinical,
policy and public health questions. Typical questions at level of the
individual child include:

- What is the gain in development since the last measurement? 

- What is the difference in development between two children of the
same age?

- How does the child's development compare to a norm group?

- How will this child's develop further?

Studies aiming to identify determinant or establish effects typically
formulate questions at the group level. Examples are:

- What is the effect of an intervention on child development?

- What is the difference in child development between specific groups?

Monitoring population health is typically executed done at the
municipal, regional or country level. Relevant questions at these
levels include:

- What is the change in average child development since the last
measurement?

- What is the effect of different policies on child development?

- How does the population compare relative to a global standard for
child development?

Note that all questions compare the level of child development in some
way. A few questions compare development for the same
child/group/population at different ages. Some others compare
development within the same age across different children, group 
or populations.

In the ideal situation, we would have one unit for child development.
Let us name this unit *D*, for development. Unit *D* should have the
following desirable properties:

- Difference between two *D*-scores measured on the same child at
different ages quantifies the amount of development during the
interval

- Difference between the *D*-score measured on two different children
of the same age quantifies the difference in development between them

- Comparing the *D*-score to an age-dependent reference identifies
abnormal development

These properties will be satisfied if we measure development on an
interval scale, i.e., a scale with a constant unit. The interpretation
of the difference between two *D*-score is the same across the entire
scale, just like differences in height or weight. 

If we succeed in creating an interval scale for development, then an
enormous arsenal of technique developed for quantitative variables
opens up to measure, track and analyze child development.

## A new model for development

Chapter 2 reviewed the age-based and score-based approaches to the
measurement of child development. Neither approach provides a unit for
child development. Age-based measurement expresses development in
age-equivalents, whose precise definition depends on the reference
population. Score-based measurement measure by summing the number of
passes, but different instruments make different selections of items,
so the measurements are unique to the instruments, and cannot be
compared across instruments. Both approaches only provide arbitrary
measures.

In order to make progress, what we need is the definition of a unit of
child developent, and an operationalization how each measurement item
related to the unit. If we success in this, we are able to construct
different instruments that yields measurement in a common unit. The
next section introduce the basic concepts for this new approach.

### The latent variable, and its role in measurement

In this booklet we define measurement as the process of locating both
persons and items on a line that represents a *latent variable*. The
latent variable reflects the construct that the scale is designed to
measure. In our case, the concept is *child development*, but other
constructs, like *height*, *temperature* or *happiness* are equally
valid constructs.

A latent variable ranges from low to high, and preferably having a
constant unit so that the interpretation of a difference between two
scores is identical across the entire scale. A latent variable cannot
be measured directly. It is a theoretical construct. However, observed
(or manifest) variables can be measured. e.g., the child's scores on a
set of developmental items in a test.

The observed data may show typical patterns, like correlations, and
the idea is that these patterns can be explained by a single
underlying variable, the latent variable. The models that relate the
manifest variables to the latent variable express the probability of
passing a test item as a function of the difference between the
person's ability and the item's difficulty. Given the values on a set
of scores for a particular child and given a particular model, the aim
is to deduce the value on the latent variable which is most likely to
have given rise to the observed data.

### Criteria for invariant measurement

Measurement is the process of assigning numbers by rules to a set of
persons or objects. This definition is a little liberal. In order to
be useful the process of assigning numbers must be bound by some
imperatives. In this booklet, we strive to achieve *invariant
measurement*, a very strict form of measurements that is subject to
the following requirements (@ENGELHARD2013, p. 14):

1. *Item-invariant measurement of persons*: The measurement of persons
must be independent of the particular items that happen to be used for
the measuring.

2. *Non-crossing persons response functions*: A more able person must
always have a better chance of success on an item that a less able
person.

3. *Person-invariant calibration of test items*: The calibration of
the items must be independent of the particular persons used for
calibration.

4. *Non-crossing item response functions*: Any person must have a
better chance of success on an easy item than on a more difficult
item.

5. *Unidimensionality*: Items and persons must be simultaneously
located on a single underlying latent variable.

A statistical model that conforms to these five requirements is said
to be an *ideal-type model*. There are only very few ideal-type
models. An ideal-type model isn't changed to fit the data, but the
data (items and persons) are selected to fit the ideal-type model.

The need for the five requirements for invariance is not universally
shared. In particular, a substantial group of statisticians questions
the need for requirements 2 and 4, especially the words "always" and
"any", and may opt for more flexible models that do not strictly
adhere to the invariance conditions 2 and 4. There are also more
flexible models that assume a multi-dimensional instead of a
unidimensional latent variable. Some investigators question all
requirements, and would rather not be restricted and place a high
value to a good fit to all data.

### Item response functions

The item response function describes the probability of passing the 
an item as a function of the ability of the child. In general, 
we expect and desire that this probability increases with ability 
(requirement 2).

Let $\beta_n$ be the ability of a child at the time of measurement. 
Suppose we have three abilities $\beta_1$, $\beta_2$ and $\beta_3$,
corresponding to $N = 3$ measurements. These could be 

1. abilities from the same child at three ages, 
2. abilities of three different children, or
3. two abilities of the same child at two age, and one ability from another child, and so on.

<!-- include here graph with beta1-beta3 with four item response curves:
guttman, rasch, 3PL and flat. Show table with probability for correct
response 3 x 4 --> 

<!-- Guttman scalogram: high-jumping tournament. The athletic who jump highest wins, and the 
assumption is that this is the athlete with the highest ability. -->

### Person response functions



### Family of item response theory models

*Ideal-type models*:

1. Guttman scalogram model (@GUTTMAN1950)

2. Rasch model (@RASCH1960) and extensions (@WRIGHT1982, @ANDRICH1988)

3. Mokken scaling model (@MOKKEN1971).

The Guttman and Mokken model yield an ordinal latent scale, while the 
Rasch model yields an interval scale (with a constant unit).


## Comparison to classic age-based approach

EXAMPLES OF AGE-BASED MEASUREMENT

Let the $Y_j$ contain the scores on the $j$-th developmental item, where $j = 1, \dots, p$. 
For the moment, let us assume that all items are binary, so that 
$Y_j = 0$ indicates a fail, and $Y_j = 1$ indicates a pass. 
Suppose we are interested in studing the relationship between age, denoted by 
variable $X$, and development as measured through items $Y_1, \dots, Y_p$.

The joint distribution $P(Y_1, \dots, Y_p, X)$ contains all relevant 
information for this problem. Age-based measurement is an attempt to model 
this joint distribution by breaking it down into $p$ conditional distributions:
$$
P(Y_1 | X)\\
\vdots\\
P(Y_p | X)\\
$$

each of which describes how the probability of passing changes with age. 
For example, @DRACHLER2007 formulated the model as a logistic regression 
model on the logarithm of age:

$$ 
\ln \frac{P(Y_j=1)}{P(Y_j=0)} = \alpha_j + \beta_j\ln X
$$

For this model, the age at which 50\% of the children pass item $j$ 
can be calculated as to $\exp(-\alpha_j/\beta_j)$. Since older children are 
expected to be more mature, this parameter is typically 
interpreted as the difficulty of the item. The slope parameter 
$\beta_j$ indicates how rapidly the probability of passing 
rises with age. Items with high $\beta_j$ have a great power to discriminate 
developmental status well within a small age range. It is straightforward
to calculate any other age-percentiles, for example, the ages 
at which probabilities 10\% or 90\% of the sample pass the item.
Table~2 in @DRACHLER2007 reports these statistics for the Denver 
developmental test.

While the idea of breaking up the test into separate items
is productive, age-based measurement has severe weaknesses. 

1. The concepts of age and development are not separated, so we 
cannot interpret the difficulty of an item without age. 
It would be more convenient, and conceptually clearer, if 
item difficulty could be a free-standing concept.

2. The models are fitted separately for each $Y_j$. Nothing 
is specified how the items relate to each other, so in principle, 
any variable that changes with age (e.g. child had first birthday) could 
qualify as a developmental item. It would be better of the 
procedure would start from a model about how the items should 
relate to each other. 

3. The intercept and slope estimates are dependent on 
the sample. A sample consisting of children of low ability
would give different estimates than a sample of children with
high ability. Calibration of test items is not person-invariant. 
It would be preferable if the difficulty estimates
were independent of the sample used to estimate them. 

4. Because of the introduction of slopes in the logistic model
a more able person may have a lower success probability for some
items than a less able person. It would be preferable if 
more able persons have a better succes rate on all items.
