# Three ways to quantify child development {#sec:threeways}

This section distinguished three different methods to quantify child
development: age-based, score-based and unit-based measurement.

## Age-based measurement of development {#sec:agebased}

The motivation for measuring child development is to be able to
describe the behavior expected at a selected age. @gesell1943 (p. 89)
formulates this goal as follows:

> We think of behavior in terms of age, and we think of age in terms
> of behavior. For any selected age it is possible to sketch a portrait
> which delineates the behavior characteristics typical of the age.

@stott1967 (p. 22) observed that it is impossible to define a scale
for measuring child development:

> When development appears as a change in kind, that is, when the 
> change consists of a series of qualitatively different events,
> or features, or "stages", it is not amemable to measurement
> by use of any standard scale of units.

As a solution Stott suggested using the "invariable sequence" of
successive stages as the basis for the assessment of the individual's
status. Stott argues that such sequences are fairly well established
for physical activity. He admits though that such stages are less
clear for the acquisition of speech and other social skills.

Since age and development are so intimately related, the *difficulty*
of developmental a given milestone is traditionally expressed in terms
of the age at which children achieve the milestone. For example,
@stott1967 (p. 25) defines the *age equivalent* and its use for
measurement, as follows:

> The age equivalent of a particular stage is simply the average age 
> at which children reach that particular stage. A set of age 
> equivalents corresponding to a series of stages can be made to 
> function as a scale for individual assessment.

Alternatives to the age equivalents include the ages at which 10, 50
or 90 percent of the children achieve the milestone. This line of
reasoning has led to the widely used concept of `developmental age` as
a measure of a child's development (in body size or motor skill or
psychological function) expressed in terms of age norms.

<!--Include numerical example here from Shirley data -->

Age-based measurement was once the dominant paradigm for measuring
child development. It is easy to understand, but is not without 
some problems and limitations.

1. Age-based measurement does not tell us what is normal for a child
at a given age. We can properly infer whether a child is early or late
for a given milestone. However, this does not give us insight which
behaviors are characteristic at the child's age.

2. Age-based measurement cannot exists without an age norm. When there
is no norms, we cannot quantify development. Age-based measurement
does not separate quantification of development from evaluation of 
development.

3. Age-based measurement only works at the item level, and is 
cumbersome to apply with multiple items.

## Score-based measurement of development {#sec:scorebased}

A second approach to measurement is to administer multiple items to
the child, and and compute the total number of PASS responses as a
measure of child's development. Items can be ordered in difficulty, so
one may skip items that are too easy, and stop when items become too
difficult. Since different children get different sets of items, one
cannot simply interpret the sum score of a measure of development.
Most instruments describe corrections that should be applied,
typically under the assumption that the child would have passed all
"too easy" items and failed on all "too difficult" items. This
procedure is typically repeated for different domains, e.g. motor,
cognitive, and so on.

<!--Include numerical example here from Shirley data -->

Score-based measurement is the dominant approach, but is not without
conceptual and logistical issues.

1. The total scores calculated by different instruments are based on
different sets of items, and hence cannot be compared. In addition,
instruments use their own age norms, but these do extend to norms for
measurements made by other instruments.

2. Domains are hard to separate. For example, some cognitive items tap
into fine motor capabilities, and vice versa. There are different ways
to define domains, so domain interpretation varies by instrument.

3. Administration of a full test may take substantial time. The
materials are often proprietary and sometimes costly.

## Unit-based measurement of development {#sec:unitbased}

Unit-based measurement starts from the premise that the measurement
scale must have a constant unit. If that holds, then the same
difference between two values has the same interpretation anywhere on
the scale. Familiar examples of such scales includes temperature and
dates. For example, the difference between two dates corresponds to
the same amount of time, irrespective of whether this is now, in the
past or in the future. The interval scale has a fixed unit and an
arbitrary zero.

In the ideal situation, we would have a unit for child development.
Let us name this unit *D*, for development. Unit *D* should have the
following desirable properties:

- Difference between two *D*-scores measured on the same child at
different ages quantifies the amount of development during the
interval

- Difference between the *D*-score measured on two different children
of the same age quantifies the difference in development between them

- Comparing the *D*-score to an age-dependent reference identifies
abnormal development

The interpretation of the difference between two *D*-score is the same
across the entire scale, just like differences in height or weight.
Note that the unit would allow us to answer all questions raised in section @\ref(sec:questions).

The development of a unit for development is still in its infancy.
However, if we succeed in creating an interval scale for development,
then an enormous arsenal of technique developed for quantitative
variables opens up to measure, track and analyze child development.

## Role of unit-based measurement {#sec:whyunit}

This section reviewed age-based, score-based and unit-based approaches
to the measurement of child development. Age-based measurement
expresses development in age-equivalents, whose precise definition
depends on the reference population. Score-based measurement
quantifies development by summing the number of passes, but different
instruments make different selections of items, so the measurements
are unique to the instruments, and cannot be compared across
instruments. Neither approach provides a unit for child development.

In order to make progress, what we need is the definition of a unit for
child developent, and an operationalization how each measurement item
related to the unit. If we success in this, we are able to construct
different instruments that yields measurement in a common metric. The
next chapter will introduce the basic concepts for this new approach.
